### ISSUE TITLE
Unable to locate httparty-0.15.6

### ISSUE THREAD

**Issue by Moumoutaru** [toddq/pico-proxy#1]
Looks like httparty might not be available. Any ideas?

`⇒  docker run --name pico-proxy -p 3000:3000 pico-proxy                           
/usr/local/lib/ruby/site_ruby/2.2.0/bundler/spec_set.rb:88:in `block in materialize': Could not find httparty-0.15.6 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/site_ruby/2.2.0/bundler/spec_set.rb:82:in `map!'
	from /usr/local/lib/ruby/site_ruby/2.2.0/bundler/spec_set.rb:82:in `materialize'
	from /usr/local/lib/ruby/site_ruby/2.2.0/bundler/definition.rb:170:in `specs'
	from /usr/local/lib/ruby/site_ruby/2.2.0/bundler/definition.rb:237:in `specs_for'
	from /usr/local/lib/ruby/site_ruby/2.2.0/bundler/definition.rb:226:in `requested_specs'
	from /usr/local/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:108:in `block in definition_method'
	from /usr/local/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:20:in `setup'
	from /usr/local/lib/ruby/site_ruby/2.2.0/bundler.rb:107:in `setup'
	from /usr/local/lib/ruby/site_ruby/2.2.0/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/bundle/bin/puma:27:in `<main>'
`

**Comment by toddq** [comment]
Looking at this made me realize I hadn't been good about pushing my local commits back up.  I also just updated some dependency versions.  Try updating the repo and building the container again (use `--no-cache` for good measure).

**Comment by Moumoutaru** [comment]
Will give it a try later!
